name: partyapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  image_picker:
  custom_switch:
  http:
  progress_dialog:
  url_launcher:
  mime:
  toast:
  intl:
  json_annotation:
  date_format:
  shared_preferences:
  cached_network_image:
  shimmer:
  flutter_launcher_icons:
  flutter_page_transition:
  connectivity:
  paytm :




dev_dependencies:
  build_runner: ^1.7.1
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - about.jpg
    - about-2.jpg
    - banner1.jpg
    - house.jpg
    - corpteparty.jpg
    - banner2.jpg
    - banner3.jpg
    - bartender.jpg
    - beverage.jpg
    - bg.jpg
    - butler.jpg
    - contact-title.jpg
    - corporateparty.jpg
    - crokerey.jpg
    - gallery_1.jpg
    - gallery_2.jpg
    - gallery_3.jpg
    - glassware.jpg
    - aboutus.png
    - services.png
    - gallery.png
    - add-friend.png
    - forgot.png
    - faqs.png
    - phone.png
    - party.png
    - edit.png
    - cart.png
    - order.png
    - setting.png
    - user.png
    - LOCK_1.png
    - gear.png
    - lock.png
    - password.png
    - phone_call.png
    - rightarrow.png
    - shopping_cart.png
    - terms.png
    - user_red.png
    - agreement.png
    - email.png
    - chat.png
    - call.png
    - cat.jpg
    - back.png
    - partylogo.jpg
    - phonesetting.png
    - logout.png
    - dakiba_logo.png
    - background.jpg
    - services_background.jpg
    - profile.png
    - menu.png
    - categorys_image.jpg
    - change_password.png
    - contact_us.png
    - back_button.png
    - home.png
    - privacy.png
    - tc.png
    - privacy_logo.png
    - tc_logo.png
    - signup_background.jpg
    - order_hist.ico
    - contact_logo.png
    - mesg.png
    - internet.jpg
    - onepic.jpeg
    - secondpic.jpeg
    - thirdpic.jpeg
    - fourthpic.jpeg
    - fivepic.jpeg
    - sixpic.jpeg
    - sevenpic.jpeg
    - thumsup.gif
    - payment_failed.gif
    - fail.png
    - right_tick.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Montserrat
       fonts:
         - asset: font/Montserrat-Bold.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
     - family: Montserrat-SemiBold
       fonts:
         - asset: font/Montserrat-SemiBold.ttf
  #         weight: 700
  #
     - family: Montserrat-Medium
       fonts:
         - asset: font/Montserrat-Medium.ttf

#     - family: SingleDemo-SemiBold
#       fonts:
#         - asset: font/SingleDemo-SemiBold.otf

     - family: AlkesDemo-SemiBold
       fonts:
         - asset: font/AlkesDemo-SemiBold.ttf

     - family: MontBlancDemo-Bold
       fonts:
         - asset: font/AlkesDemo-SemiBold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  image_path: "icon/dakiba_logo.png"
  android: true
  ios: true